apiVersion: v1
data:
  DATABASE: infra-manager
  HOST: kumarandev.public.2fda97ccf1cc.database.windows.net
  PASSWORD: 'appinfra@123'
  PORT: '3342'
  USER: infra_manager_app
  ENV: DEV
kind: ConfigMap
metadata:
  name: infra-manager-config
  namespace: infra-manager




